import Link from "next/link";
import { Badge, Empty, fmtDate, PageHeader, Pagination, Panel, TableWrap } from "@/components/admin/AdminShell";
import styles from "../admin.module.css";
import { getUsers, teacherJourneyLabel } from "@/lib/admin-data";
import { requireAdmin } from "@/lib/admin-auth";

type Params={q?:string;plan?:string;status?:string;page?:string;tab?:string};
export default async function UsersPage({searchParams}:{searchParams:Promise<Params>}){
  await requireAdmin("/admin/pengguna");const p=await searchParams,data=await getUsers({q:p.q,plan:p.plan,status:p.status,page:Number(p.page)||1}),tab=p.tab??"guru";
  return <><PageHeader eyebrow="Akaun & akses" title="Pengguna" description="Guru, identiti pelajar minimum daripada respons, dan sejarah langganan dalam satu tempat." actions={<a className={styles.secondaryButton} href={`/api/admin/export?type=${tab}`}>Export CSV</a>}/>
    <nav className={styles.subnav}><Link href="/admin/pengguna?tab=guru">Guru</Link><Link href="/admin/pengguna?tab=pelajar">Pelajar</Link><Link href="/admin/pengguna?tab=langganan">Langganan</Link></nav>
    {tab==="guru"?<Panel title="Senarai guru" description={`${data.total} akaun ditemui`}><form className={styles.filters}><input name="q" placeholder="Cari nama atau email" defaultValue={p.q}/><select name="plan" defaultValue={p.plan??"all"}><option value="all">Semua pakej</option><option value="free">Free</option><option value="plus">Plus</option><option value="pro">Pro</option></select><select name="status" defaultValue={p.status??"all"}><option value="all">Semua status</option><option value="active">Aktif</option><option value="expired">Tamat</option><option value="none">Tiada langganan</option></select><button>Tapis</button></form>{data.rows.length?<><TableWrap><table><thead><tr><th>Guru</th><th>Daftar</th><th>Perjalanan terakhir</th><th>Pakej</th><th>Aktiviti</th><th>Login terakhir</th><th></th></tr></thead><tbody>{data.rows.map(r=>{const journey=Number(r.activities)>0?"Kuiz diterbitkan":Number(r.ai_generated)>0?"AI berjaya, belum diterbitkan":teacherJourneyLabel(r.journey_stage,r.journey_message);return <tr key={r.id}><td><b>{r.name}</b><br/><small>{r.email}</small></td><td>{fmtDate(r.created_at)}</td><td><Badge value={journey}/><br/><small>{r.journey_at?fmtDate(r.journey_at):"Belum ada langkah selepas login"}</small></td><td>{r.plan_id}</td><td>{r.activities}</td><td>{fmtDate(r.last_login_at)}</td><td><Link href={`/admin/pengguna/${r.id}`}>Butiran →</Link></td></tr>})}</tbody></table></TableWrap><Pagination page={data.page} pages={data.pages} base="/admin/pengguna" params={{q:p.q,plan:p.plan,status:p.status}}/></>:<Empty/>}</Panel>:null}
    {tab==="pelajar"?<Panel title="Pelajar" description="Sistem belum mempunyai profil pelajar berasingan; hanya rekod respons minimum disimpan."><div className={styles.notice}>Nama pelajar tidak disenaraikan di halaman umum ini bagi meminimumkan pendedahan data kanak-kanak. Ringkasan aktiviti tersedia di menu Aktiviti.</div><Empty text="Tiada collection profil pelajar dalam schema semasa."/></Panel>:null}
    {tab==="langganan"?<Panel title="Langganan" description="Status dikira daripada tarikh tamat dan pembatalan.">{data.subscriptions.length?<TableWrap><table><thead><tr><th>Guru</th><th>Pakej</th><th>Status</th><th>Mula</th><th>Tamat</th><th>Baki</th><th>Sumber</th><th>Transaksi</th></tr></thead><tbody>{data.subscriptions.map(r=><tr key={r.id}><td>{r.name}<br/><small>{r.email}</small></td><td>{r.plan_id}</td><td><Badge value={r.cancelled_at?"Dibatalkan":r.days_left<=0?"Tamat":r.days_left<=3?"Akan tamat":"Aktif"}/></td><td>{fmtDate(r.starts_at)}</td><td>{fmtDate(r.ends_at)}</td><td>{r.days_left} hari</td><td>{r.source}</td><td>{r.payment_order_id??"Manual"}</td></tr>)}</tbody></table></TableWrap>:<Empty/>}</Panel>:null}
  </>;
}
